CBERS DN Metadata
brazil-data-cube/metadata pull request #76
Opened 2024-10-15 14:32 UTC by marujore

Several CBERS Digital Number metadata.
Closes #49 
Closes #50 
Closes #51
Closes #52 
Closes #53
Closes #54 
Closes #55
Closes #56 
Closes #57
Closes #58 
Closes #59
Closes #60 
Closes #61
Closes #62 
Closes #63
Closes #64 
Closes #65

2024-10-15 14:38 UTC, marujore commented
Adapted from https://github.com/brazil-data-cube/collection-register/tree/master/examples/cdsr

2024-10-17 17:36 UTC, jefersonarcanjo requested changes

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb2b-hrc-l2-dn.json
> +    "description": "CBERS-2B/HRC - Level-2 Digital Number product over Brazil.",
Over Brasil and South America

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb2b-hrc-l2-dn.json
> +            "resolution_x": 2.7,
a resolucao nominal da HRC é de 2.7m, mas no ms3 o pixel é reamostrado pra 2.5m, qual informacao colocar?

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb2b-wfi-l2-dn.json
> +    "description": "CBERS-2B/WFI - Level-2 Digital Number product over Brazil.",
...and part of South America

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l2-dn.json
> +    "description": "CBERS-4/MUX - Level-2 Digital Number product over Brazil.",
and part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l2-dn.json
> +    "quicklook": [
composicao correta seria 7,8,5

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l2-dn.json
> +            "bands": {
composicao 7,8,5

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l4-dn.json
> +    "description": "CBERS-4/MUX Level-4 Digital Number product over Brazil.",
aqui pode falar que a colecao é orthorretificada, pra diferenciar do L2.

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l4-dn.json
> +    "quicklook": [
composicao 7,8,5

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-mux-l4-dn.json
> +            "bands": {
7,8,5

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-pan10m-l2-dn.json
> +    "description": "CBERS-4/PAN10M - Level-2 Digital Number product over Brazil.",
part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-pan10m-l4-dn.json
> +    "description": "CBERS-4/PAN10M - Level-4 Digital Number product over Brazil.",
produto ortorretificado

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-pan5m-l2-dn.json
> +    "description": "CBERS-4/PAN5M - Level-2 Digital Number product over Brazil.",
over part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-pan5m-l4-dn.json
> +    "description": "CBERS-4/PAN5M - Level-4 Digital Number product over Brazil.",
part of South America and orthorretified

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-wfi-l2_dn.json
> +    "description": "CBERS4/WFI Level-2 Digital Number product over Brazil.",
part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4-wfi-l4-dn.json
> +    "description": "CBERS4/WFI Level-4 Digital Number product over Brazil.",
part of SA and orthorretified

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l2-dn.json
> +    "description": "CBERS-4A/MUX - Level-2 Digital Number product over Brazil.",
part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l2-dn.json
> +    "quicklook": [
composicao correta : 7,8,6

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l2-dn.json
> +            "resolution_x": 16.5,
pixel size no MS3 esta definido como 16 m

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l2-dn.json
> +                "red": "BAND5",
RGB 7,8,6

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l4-dn.json
> +    "description": "CBERS-4A/MUX - Level-4 Digital Number product over Brazil.",
over part of SA and orthorretfied

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l4-dn.json
> +    "quicklook": [
RGB : 7,8,6

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-mux-l4-dn.json
> +            "resolution_x": 16.5,
Pixel size = 16m

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wfi-l2-dn.json
> +    "description": "CBERS-4A/WFI Level-2 Digital Number product over Brazil.",
and part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wfi-l2-dn.json
> +    "quicklook": [
RGB : 15, 16, 14

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wfi-l2-dn.json
> +            "bands": {
RGB 15,16,14

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wfi-l4-dn.json
> +    "description": "CBERS-4A/WFI Level-4 Digital Number product over Brazil.",
over part of SA and ortho...

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wfi-l4-dn.json
> +    "quicklook": [
RGB 15,16,14

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wpm-l2-dn.json
> +    "description": "CBERS-4A/WPM - Level-2 Digital Number product over Brazil.",
and part of SA

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wpm-l2-dn.json
> +    "quicklook": [
RGB: 3,4,2

2024-10-17 17:36 UTC, jefersonarcanjo commented on cb4a-wpm-l2-dn.json
> +            "bands": {
RGB 3,4,2

2024-10-17 17:55 UTC, marujore commented on cb2b-hrc-l2-dn.json
> +            "resolution_x": 2.7,
vou mudar para 2.5, pois é a info fornecida da imagem

2025-01-03 12:57 UTC, merged